variable "project" {
  description = "The project in which to hold the components"
  type        = string
}

variable "region" {
  description = "The region in which to create the VPC network"
  type        = string
  default     = "us-central1"
}

variable "zone" {
  description = "The zone in which to create the Kubernetes cluster. Must match the region"
  type        = string
  default     = "us-central1-a"
}

variable "environment" {
  description = "Name of the environment"
  type        = string
  default     = "dev"
}

variable "cluster_name" {
  description = "The name to give the new Kubernetes cluster."
  type        = string
  default     = "private-cluster"
}

variable "bastion_tags" {
  description = "A list of tags applied to your bastion instance."
  type        = list
  default     = ["bastion"]
}

variable "service_account_iam_roles" {
  description = "List of the default IAM roles to attach to the service account on the GKE Nodes."
  type        = list
  default = [
    "roles/logging.logWriter",
    "roles/monitoring.metricWriter",
    "roles/monitoring.viewer",
    "roles/container.admin",
    "roles/container.clusterAdmin",
    "roles/storage.admin"
  ]
}

variable "project_services" {
  description = "The GCP APIs that should be enabled in this project."
  type        = list
  default = [
    "cloudresourcemanager.googleapis.com",
    "servicenetworking.googleapis.com",
    "container.googleapis.com",
    "gkeconnect.googleapis.com",
    "gkehub.googleapis.com",
    "endpoints.googleapis.com",
    "compute.googleapis.com",
    "iam.googleapis.com",
    "logging.googleapis.com",
    "monitoring.googleapis.com",
    "securetoken.googleapis.com",
    "file.googleapis.com"
  ]
}

variable "gke_private_subnet" {
  default = "10.1.0.0/21"
}

variable "gke_public_subnet" {
  default = "10.1.8.0/21"
}

variable "boomi_authentication_type" {
  description = "Boomi Platform Authentication Type(Either password or token)"
  type        = string
}

variable "boomi_mfa_install_token" {
  description = "An MFA installation token generated by your Dell Boomi Administrator."
  type        = string
}

variable "boomi_account_id" {
  description = "The Boomi account ID that you want to associate with the new Molecule cluster."
  type        = string
}

variable "boomi_username" {
  description = "The email account associated with the Boomi account."
  type        = string
}

variable "boomi_password" {
  description = "The password associated with the Boomi account."
  type        = string
}
